### ISSUE TITLE
How did you estimate the z value of POF?

### ISSUE THREAD

**Issue by wine3603** [CMU-Perceptual-Computing-Lab/MonocularTotalCapture#10]
Hi guys,
in the paper's section 4, after the definition of POF, it was said this paper use 3 channels to estimate POF instead of 2 in OpenPose.  it didnot show how to estimate the depth “z" from the single rgb image,  does it from the dataset groundtruth?

**Comment by xiangdonglai** [comment]
Yes, the POF heatmap is trained in a supervised way, including the 'z' channels for each bone.
