### ISSUE TITLE
Is it possible to release training code instead of pretrained model zip?

### ISSUE THREAD

**Issue by shiyiyuedeyu** [CMU-Perceptual-Computing-Lab/MonocularTotalCapture#19]
Hello,
    I am wandering if I could train the net by myself. I have run  MonocularTotalCapture and it performed well. As a result, I am interested in training MTC locally.

**Comment by xiangdonglai** [comment]
Hi, although the release of training code is not in our original plan, I have pushed my training code to a new branch called 'training'. The main code to train our body network is 'POF/training_e2e_PAF.py', and to train our hand network we use 'POF/training_PAF_hand.py'.

It might be a little bit tricky but you need to figure out how we feed the data into our network using 'POF/data/DomeReader.py', 'POF/data/HumanReader.py', and 'POF/data/COCOReader.py'. Our dome dataset can be downloaded from our [project website](http://domedb.perception.cs.cmu.edu/mtc.html), and need to be processed using 'POF/data/collect_a4.py' script; the Human3.6M is [this version](https://github.com/geopavlakos/c2f-vol-train). Some paths in the files are coded for our own server, but it should be easy to figure out how to change to your own paths.

**Comment by shiyiyuedeyu** [comment]
> Hi, although the release of training code is not in our original plan, I have pushed my training code to a new branch called 'training'. The main code to train our body network is 'POF/training_e2e_PAF.py', and to train our hand network we use 'POF/training_PAF_hand.py'.
> 
> It might be a little bit tricky but you need to figure out how we feed the data into our network using 'POF/data/DomeReader.py', 'POF/data/HumanReader.py', and 'POF/data/COCOReader.py'. Our dome dataset can be downloaded from our [project website](http://domedb.perception.cs.cmu.edu/mtc.html), and need to be processed using 'POF/data/collect_a4.py' script; the Human3.6M is [this version](https://github.com/geopavlakos/c2f-vol-train). Some paths in the files are coded for our own server, but it should be easy to figure out how to change to your own paths.

That's awesome! Thank you!
