### ISSUE TITLE
OpenCV / Cuda Version

### ISSUE THREAD

**Issue by j-min** [CMU-Perceptual-Computing-Lab/MonocularTotalCapture#2]
What are the versions of OpenCV / Cuda used in this project?

![image](https://user-images.githubusercontent.com/18069263/60274399-f3d8d880-9932-11e9-8792-689a4f153c35.png)
In the [the current Dependency list](https://github.com/CMU-Perceptual-Computing-Lab/MonocularTotalCapture/tree/3022330e6ebcb46034ad332006f0e119289d0e5b#dependencies) OpenCV appears twice.

1) OpenCV for Python 3.5
2) OpenCV 2.4.13 (Compiled with CUDA)

However, Python 3 has been supported since OpenCV > 3.
Did you install two different OpenCV?
Specifically,
1) OpenCV (which version? / CUDA compiled?) with Python 3.5
2) OpenCV 2.4.13 with CUDA (which version?) with Python 2.7

**Comment by xiangdonglai** [comment]
Yes, we do use 2 version of OpenCV.

OpenCV 2.4.13 was compiled from source with CUDA 9.0, CUDNN 7.0. It is used in our C++ code.

OpenCV for python 3.5 was installed via pip3; the exact version is 3.4.2.17. This version is used in python code.
`pip3 install opencv-contrib-python==3.4.2.17`

**Comment by j-min** [comment]
Thanks, this is really helpful!
Can you also let us know the version of gcc?
Did you use same gcc for compiling OpenCV, openpose, Ceres-Solver and libigl?

Also, in which order did you compile the dependencies? I don't think the order should matter, but it can give the hint of using wrong version of something to users in early stages.
In my case, with gcc-6 and CUDA 10.1, I could install everything but OpenCV 2.4.13.
And now I am installing from the beginning with CUDA 9.0 and CUDNN 7.5 (and trying different versions of gcc).

**Comment by xiangdonglai** [comment]
I was using g++ 5.4.0 for all the C++ dependencies.

Unfortunately I don't remember the order of installation, but clearly OpenCV must be installed before OpenPose, Eigen3 must be installed before Ceres; other than these, the order does not seem to matter too much.

**Comment by j-min** [comment]
I cannot compile openpose [current master](https://github.com/CMU-Perceptual-Computing-Lab/openpose/tree/c4369cba19ba74cdcccae271d519657915aa6b9e) with g++ 5.5.
However, it can be compiled with g++ 6.5. Could you please confirm your openpose version?

**Comment by j-min** [comment]
Never mind. I finally succeeded to run `run_pipeline.sh` with dependencies compiled with different g++!
