### ISSUE TITLE
I have trouble in training.

### ISSUE THREAD

**Issue by BUPT-ZJie** [CMU-Perceptual-Computing-Lab/MonocularTotalCapture#22]
Hello,
I am very curious about where is the “openpose_body_3DPAF_randomz_headtop_chest.npy”  mentioned in  "training_e2e_PAF.py". And I am wondering why  "snapshots/PAF_body_headtop_domehumanCOCO_chest_noPAF/model-100000" is not found if fine_tune is true.

**Comment by xiangdonglai** [comment]
'openpose_body_3DPAF_randomz_headtop_chest.npy' (not in the repo) is a set of network weight modified from the original OpenPose network. We modify the weight to add new 2D keypoint channels, and change the 2 channels per PAF to 3 channels per POF, with the new weights randomly initialized.

When you first train the network 'fine_tune' should be False.

**Comment by BUPT-ZJie** [comment]
Okay, I see. Thank you.
