### ISSUE TITLE
[HELP] motion capture output for motion retargeting

### ISSUE THREAD

**Issue by seong-heum** [CMU-Perceptual-Computing-Lab/MonocularTotalCapture#23]
I thank you for the greatest work, "Monocular Total Capture: Posing Face, Body and Hands in the Wild." Especially, I saw your motion retargeting result in YouTube and it was so amazing!!

Could you tell me how to convert your motion capture output (0000.txt) to a blender-readable format (e.g. .BVH) for motion retargeting? It would be really really grateful if you share just one .BVH or .FBX file for the Mixamo template as demonstrated in the Youtube video.

Hopefully I can reproduce/extend the motion retargeting part based on your Adam model. Thank you.

**Comment by xiangdonglai** [comment]
Please refer to this previous issue #6. We have a utility class BVHWriter in our code that can automatically generate BVH file from our Mocap output. It should be easy to use by just calling:
```
// 'g_total_model' is an object of Adam model
BVHWriter bvhwriter(g_total_model.m_parent);
// 'J0_vec' is the T-pose skeleton, 'ts' and 'poses' are vectors of global translation and pose parameters for different time steps.
bvhwriter.parseInput(J0_vec, ts, poses);
bvhwriter.writeBVH(std::string("temp.bvh"), 1.0/30);
```
For more detail you can refer to the original post #6. If anything is still not clear you can further contact me.

**Comment by seong-heum** [comment]
Oh I've not read previous Q&A. I can try it as you suggest.

**Comment by xiangdonglai** [comment]
Hi Seong-heum,

I've provided an example to use our BVH exporter in the repo, 'FitAdam/bvh.cpp'. After recompiling the C++ project, you can 'cd FitAdam/' and run './build/bvh'; it will generate an 'output.bvh' file containing the first 10 frames of the dancing sequence (assuming you have already generated our estimation result).

**Comment by seong-heum** [comment]
Thank you very much for offering to help out with this issue!
