### ISSUE TITLE
Pythown Wrapper - "libPythonWrapper.so" file missing

### ISSUE THREAD

**Issue by BenSaunders27** [CMU-Perceptual-Computing-Lab/MonocularTotalCapture#26]
Hi,

I am trying to use the python wrappers to visualise the outputs of MTC. However, in AdamModel.py, it seems I need a **"libPythonWrapper.so"** file to initialise the meshWrapper:

meshlib = meshWrapper("/home/donglaix/Documents/Experiments/hand_model/build/libPythonWrapper.so") (line 239 of AdamModel.py)

I have compiled the code but cannot seem to find this required file. Can you advise where I would be able to access/generate the "libPythonWrapper.so" file?

Thanks,
Ben

**Comment by heathentw** [comment]
I had the same question while trying to render the visualization results (of the whole body).

**Comment by xiangdonglai** [comment]
Hi all. I have pushed the source file of the C++ shared library. You can recompile the C++ project and will find it in 'build' folder.
