### ISSUE TITLE
run_pipeline.sh: line 58: 16476 Segmentation fault(core dumped) 

### ISSUE THREAD

**Issue by wtnan2003** [CMU-Perceptual-Computing-Lab/MonocularTotalCapture#33]
After successful installation run
```bash run_pipeline.sh example_dance```

Everything seems to be ok and start running every frame like :

``` 
...
Start running frame No. 00000403
PAF_type 0
LK left hand failed.
LK right hand failed.
PAF_type 0
PAF_type 0
...
```
Then a window came out but immediately close and output:
```
Root Directory: /home/nd/MonocularTotalCapture/data
Sequence Name: example_dance
run_pipeline.sh: line 58: 16476 Segmentation fault  (core dumped) 
./build/run_fitting --root_dirs $dataDir --seqName $seqName --start 1 --end $((numFrame +1)) --stage 1 --imageOF                                                                                                                            

```

And I try to output bvh file by 
```
./build/bvh
```
bvh: /home/nd/MonocularTotalCapture/FitAdam/src/simple.cpp:224: void readFrameParam(std::__cxx11::string, smpl::SMPLParams&): Assertion `f.good()' failed.
Aborted (core dumped)

![image](https://user-images.githubusercontent.com/20351890/71657744-264d0d80-2d7c-11ea-89dc-a8980945ccb7.png)

Any help would be greatly appreciated.

**Comment by wtnan2003** [comment]
remote operations cause

**Comment by kyeongeunn** [comment]
> remote operations cause

could I know how did you solve the problem? 
I faced the same problem...

**Comment by wtnan2003** [comment]
@kyeongeunn  It seems that you are running our code on a machine with no display (such as remote server). Unfortunately, this version of OpenGL library works only on a machine with a monitor. Please try a machine like that.

**Comment by kyeongeunn** [comment]
> @kyeongeunn It seems that you are running our code on a machine with no display (such as remote server). Unfortunately, this version of OpenGL library works only on a machine with a monitor. Please try a machine like that.

Thank you for your comment. I'm so greatly appreciated. I will try it like your mention.
