### ISSUE TITLE
Model fitting from 3D point cloud

### ISSUE THREAD

**Issue by ryohachiuma** [CMU-Perceptual-Computing-Lab/MonocularTotalCapture#4]
Hi, do you plan to provide the optimization code for fitting Adam model from 3D point cloud?
That is to say, will you release the code of TotalCapture?
http://openaccess.thecvf.com/content_cvpr_2018/papers/Joo_Total_Capture_A_CVPR_2018_paper.pdf

Or do you know the source code which estimates SMPL parameters from 3D point cloud?

**Comment by xiangdonglai** [comment]
Hi, thank you for your interest in our work. There is no plan for us to release the code for the CVPR 18 paper.

I don't know any official code released from MPI people on registering SMPL to point cloud.
