### ISSUE TITLE
How to get 3D joint positions?

### ISSUE THREAD

**Issue by cbsudux** [CMU-Perceptual-Computing-Lab/MonocularTotalCapture#42]
I want to visualize 3D joint positions (3D pose). How do I do this?

**Comment by xiangdonglai** [comment]
After GenerateMesh function is called, for example here:
https://github.com/CMU-Perceptual-Computing-Lab/MonocularTotalCapture/blob/master/FitAdam/run_fitting.cpp#L589

the 3D joint positions are stored in 'gResultJoint'.

**Comment by cbsudux** [comment]
Okay thanks. What's the format of the 3d joints?  I see that you've defined gResultJoint here [FitAdam/run_fitting.cpp#L43](https://github.com/CMU-Perceptual-Computing-Lab/MonocularTotalCapture/blob/master/FitAdam/run_fitting.cpp#L43) as double gResultJoint[21 * 3 + 2 * 21 * 3].

Are the first 63 elements x,y,z coordinates?

**Comment by hellozjj** [comment]
@xiangdonglai  Is the 3D joint positions gResultJoint in the world coordinate or in the camera coordinate?

**Comment by visonpon** [comment]
Hi @xiangdonglai @cbsudux, I also would like  to know how to get the 3d joints position, hope you guys can give some advice, thanks~

**Comment by xiangdonglai** [comment]
As we discussed in the post above, the joint position is stored in `gResultJoint` with each joint in 'x,y,z' order. We are using a single coordinate frame (camera coordinate) here.

**Comment by visonpon** [comment]
Hello, I have tried to save the gResultjoint from run_fitting.cpp, when try to use the root position on my own model, the result seems bad, but the defalt visualized result looks normal.
I got the root postion using the following scripts:
`int root[3]={*gResultjoint ,*(gResultjoint +1),*(gResultjoint +2)}`
Am I right? if this is right, hope you can help to give some advice,thnanks~

**Comment by xiangdonglai** [comment]
> Hello, I have tried to save the gResultjoint from run_fitting.cpp, when try to use the root position on my own model, the result seems bad, but the defalt visualized result looks normal.
> I got the root postion using the following scripts:
> `int root[3]={*gResultjoint ,*(gResultjoint +1),*(gResultjoint +2)}`
> Am I right? if this is right, hope you can help to give some advice,thnanks~

For safety I would suggest to keep the data type to double instead of int to avoid the loss of precision (I don't quite remember which unit I was using, if I was using meter then this will certainly cause some problem).

If this is not the problem, my suggestion is that you can visualize the location of your saved point in any graphical tools (such as meshlab) and compare with the saved human mesh to see whether the result makes sense.
