### ISSUE TITLE
What is the difference between openpose and this?

### ISSUE THREAD

**Issue by delebash** [CMU-Perceptual-Computing-Lab/MonocularTotalCapture#43]
Is it because this program makes 3d keypoints bvh file vs 2d key points from openpose.

I really do not know much about this type of program, I am more focused on using the application to send to unity, so pleasebe patient if I don't understand the terminology

**Comment by xiangdonglai** [comment]
Yes. In this work we estimate the 3D keypoint locations of the person, while in openpose everything is in 2D.
