### ISSUE TITLE
No facial animation obtained

### ISSUE THREAD

**Issue by jgallegov** [CMU-Perceptual-Computing-Lab/MonocularTotalCapture#44]
Hello, 
thank you for your method. I tried the examples, and everything worked well except for the facial animation. I don't know why but the facial expression is not detected. 
Please, do you know why this is happenning?

Thank you,

James

**Comment by xiangdonglai** [comment]
Sorry but as we explain in the readme: https://github.com/CMU-Perceptual-Computing-Lab/MonocularTotalCapture#adam-model

We cannot release the face part of Adam model due to copyright issue. No facial expression can be captured in this released version.
