### ISSUE TITLE
posefs1.perception.cs.cmu.edu/mtc seems down, alternative site?

### ISSUE THREAD

**Issue by carlosedubarreto** [CMU-Perceptual-Computing-Lab/MonocularTotalCapture#59]
Hi, I'm trying to build MTC bur I had problems at the first pass, the download phase.
I cant find the files needed in dowload.sh. seems that posefs1.perception.cs.cmu.edu is down.

does anybody has an alternative site for download?
I searched a lot but cant find another place with those files.

Thanks.

**Comment by jamalknight** [comment]
Same here .. looking for a way to download...
posefs1.perception.cs.cmu.edu is not available

**Comment by visonpon** [comment]
also cannot reach the site, hope can solve it, thanks ~

**Comment by xiangdonglai** [comment]
Hey guys, thank you for your interest, we are migrating the server to a new room, so link is temporarily down. We expect to restore the service early next week. Sorry for the inconvenience.

**Comment by carlosedubarreto** [comment]
Thanks a lot for the information!!!!

**Comment by ykk648** [comment]
waiting for the response.

**Comment by jionie** [comment]
waiting for the response.

**Comment by icech** [comment]
waiting for the response.

**Comment by xiangdonglai** [comment]
Hi everyone. The machines are back online after migration. Thank you for your patience.
