### ISSUE TITLE
Unable to download data. http://posefs1.perception.cs.cmu.edu/mtc/mtc_snapshots.zip Timeouts

### ISSUE THREAD

**Issue by MikeCooper18** [CMU-Perceptual-Computing-Lab/MonocularTotalCapture#65]
Attempting to download the data via the download.sh script, seems like the connection keeps timing out (http://posefs1.perception.cs.cmu.edu/mtc/mtc_snapshots.zip). Is there another source of this data?
Issue persists on multiple machines and networks.

**Comment by xiangdonglai** [comment]
Hi sorry for the network issue. I have updated the URL. Please pull the latest download script and try again. Thank you!
