### ISSUE TITLE
2D openpose keypoints vs. body2d_pred_v keypoints

### ISSUE THREAD

**Issue by cauchy0916** [CMU-Perceptual-Computing-Lab/MonocularTotalCapture#7]
Hi,

Thank a lot for disclosing the MTC code. It is really helpful to understand your wonderful work.

The code estimates two 2D keypoints from the input:
1) 2D keypoints running "OpenPose" (See Fig. 1),
2) 2D keypoints running "POF generation" (See Fig. 2).
They do not always the same 2D keypoint results, missing some keypoints shown in Fig. 2. And, in this case, the 3D fitting also goes wrong (See Fig. 3).

Question: 
1) Why do you re-estimate 2D keypoints like Fig. 2? Is it closely related with the POF calculation? 
2) Also, in the current code, body_zoom is set to 1.8. Is it manually chosen?

![outdoors_fencing_01_0007](https://user-images.githubusercontent.com/47620483/60656608-b3291400-9e8a-11e9-8155-04472b8bb526.png)
[Fig. 1. 2D keypoints from OpenPose]
![0007](https://user-images.githubusercontent.com/47620483/60656651-c936d480-9e8a-11e9-9156-629938f67d42.png)
[Fig. 2. 2D keypoints from POF generation]
![0007](https://user-images.githubusercontent.com/47620483/60656662-cf2cb580-9e8a-11e9-806b-ce36a758712d.png)
[Fig. 3. 3D fitting without temporal tracking]

**Comment by xiangdonglai** [comment]
Thank you for your interest in our work.

1. Theoretically, we need just one set of 2D keypoints. In practice, first, we found that there are often times when our 2D hand keypoints are more accurate than the original results as our model is trained with more data. Second, we believe that training our network with both 2D keypoints tasks and 3D POF can be helpful. For simplicity, we just used our own network output, but you can definitely integrate OpenPose and other information as well.

2. That number was manually chosen empirically.
