### ISSUE TITLE
undefined reference to loadTotalModelFromObj

### ISSUE THREAD

**Issue by quyanqiu** [CMU-Perceptual-Computing-Lab/MonocularTotalCapture#8]
Hi,guys,when I compile your code in CentOS7,at the final link step it said:

undefined reference to "loadTotalModelFromObj"
undefined reference to "loadModelColorFromObj"
undefined reference to "loadTotalDataFromJson"
undefined reference to "loadCocoPlusRegressor"
undefined reference to "writeFrameParam"
undefined reference to "readFramParam"

do you know how to fix that?

**Comment by xiangdonglai** [comment]
The functions are all there:
https://github.com/CMU-Perceptual-Computing-Lab/MonocularTotalCapture/blob/cc27905f5ea9eb6cbd020008ff5f23e367691cc5/FitAdam/src/totalmodel.cpp#L513
https://github.com/CMU-Perceptual-Computing-Lab/MonocularTotalCapture/blob/cc27905f5ea9eb6cbd020008ff5f23e367691cc5/FitAdam/src/simple.cpp#L202

You might want to make sure those files are correctly added to the library and compiled
https://github.com/CMU-Perceptual-Computing-Lab/MonocularTotalCapture/blob/cc27905f5ea9eb6cbd020008ff5f23e367691cc5/FitAdam/CMakeLists.txt#L34

**Comment by quyanqiu** [comment]
actually other function in simple.cpp and totalModel.cpp can be linked successfully,only these six function can not be found reference,that's so weired
