### ISSUE TITLE
body_3d_frontal_tracking images different than expected from the shown demo

### ISSUE THREAD

**Issue by MichalisLazarou** [CMU-Perceptual-Computing-Lab/MonocularTotalCapture#9]
I managed to run the demo, run_pipeline.sh for the example_speech but I noticed that the results I got for the images in body_3d_frontal_tracking are different than what can be seen in the video demo. For example there is not face variation, the mouth remains always closed and a lot of the images show completely different poses which seems as if the temporal tracking is not really workin. I was wondering if there is a reason behind this, such as setting any parameter before running run_pipeline.sh and if there is something I can do to get the results as shown in the video demo?

I attach some of the images I get here: 
![0026](https://user-images.githubusercontent.com/20433890/61217615-fa739800-a707-11e9-99c9-d83d1feb4228.png)
![0047](https://user-images.githubusercontent.com/20433890/61217646-0a8b7780-a708-11e9-9855-1a95cb56e490.png)

**Comment by xiangdonglai** [comment]
Did you add the '-f' flag for this case?

See this: https://github.com/CMU-Perceptual-Computing-Lab/MonocularTotalCapture#examples

**Comment by MichalisLazarou** [comment]
Thanks for that, I am not sure if I used the -f flag I will run it again and let you know what I get. Nevertheless how is this affecting the face expressions though?

**Comment by MichalisLazarou** [comment]
I run it again using the -f flag and I still get very similar results, with very wrong poses and no facial expressions. I would also like to note that I use the openpose CPU version to get the results.

**Comment by xiangdonglai** [comment]
Can you delete all intermediate results before running again? Some intermediate results might be cached.

**Comment by xiangdonglai** [comment]
For facial expression, as we have explained [here](https://github.com/CMU-Perceptual-Computing-Lab/MonocularTotalCapture#adam-model), we are unable to open-source the facial model.

**Comment by MichalisLazarou** [comment]
Thanks a lot for the help, I run it again and actually that was the problem it worked well with the -f flag and deleting all the intermediate results. I'm closing this issue now, again thanks!

**Comment by sunshinnnn** [comment]
Hi Donglai and Michalis, I wonder if you could figure out the place of blending weight of mesh(**totalmodel**).
Specifically, I cannot find the data source of [blendW_data](
https://github.com/seamanj/MonocularTotalCapture/blob/master/FitAdam/src/totalmodel.cpp#:~:text=extern%20const%20double%20blendW_data%5B%5D%3B) ,[root["blendW"]](https://github.com/seamanj/MonocularTotalCapture/blob/master/FitAdam/src/totalmodel.cpp#:~:text=//%20initMatrix(totalm.m_blendW%2C%20root%5B%22blendW%22%5D)%3B) or [m_blendW](https://github.com/seamanj/MonocularTotalCapture/blob/master/FitAdam/src/totalmodel.cpp#:~:text=const%20double%20w%20%3D%20totalm.m_blendW(idv%2C%20idj)%3B). Thanks!

**Comment by sunshinnnn** [comment]
I've found it finally. It's [here](https://github.com/facebookresearch/body2hands/blob/main/visualization/FitAdam/include/InitializeAdamData.h)! :)
